import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import styles from '../styles/Home.module.css'
import { getRequest } from '../utils/Network'

export default function Home() {
  let [numArray, setArray] = useState([20, 4, 17, 25, 6,45,1]) 
  let [number] = useState(17)
  
  function LoopNumber(){
    let arr2= []
    for(var i = 1; i <= number; i = i+2){
      arr2.push(i)
    }
    console.log('Bilangan Ganjil',arr2)
  }

  function Sorting(){
    numArray.sort(function(a, b) {
      return a - b;
    });

    setArray(numArray);
    console.log('Number Sorting',numArray)
  }

  const checkPalindrom = useCallback((str) => {
    if(str === str.split('').reverse().join('')){
      toast.success(`${str} Merupakan kata palindrome`)
    } else {
      toast.error(`${str} Bukan merupakan kata palindrome`)
    }
  },[])
  
  useEffect(()=>{
    LoopNumber()
    Sorting()
  },[])
  useEffect(()=>{
    checkPalindrom('sarasa')
  },[checkPalindrom])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        {/* {numArray.map((item,index)=>{
          return(
            <ul key={index}>
              <li>{item}</li>
            </ul>
          )
        })} */}
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
